include(ExternalProject)

set(X265_SOURCE_DIR ${CMAKE_SOURCE_DIR}/x265/source)
set(X265_BUILD_DIR ${CMAKE_BINARY_DIR}/x265-build)
set(X265_INSTALL_DIR ${CMAKE_BINARY_DIR}/install)
set(X265_PC_FILE ${X265_INSTALL_DIR}/lib/pkgconfig/x265.pc)

set(X265_CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${X265_INSTALL_DIR} -DENABLE_SHARED=OFF)

if(ANDROID)
    list(APPEND X265_CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DANDROID_ABI=${ANDROID_ABI}
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DENABLE_ASSEMBLY=OFF
        -DENABLE_CLI=OFF
        -DENABLE_PIC=ON
    )
    set(EXTRA_LDFLAGS "${EXTRA_LDFLAGS} -lc++ -lm" CACHE STRING "Extra linker flags for all external projects" FORCE)
    set(X265_INSTALL_COMMAND make install)
else()
    set(X265_INSTALL_COMMAND
        make install
        COMMAND ${CMAKE_COMMAND} -DX265_PC_PATH=${X265_PC_FILE} -P ${CMAKE_SOURCE_DIR}/patch_x265_pc.cmake
    )
endif()

message(STATUS "X265_CMAKE_ARGS: ${X265_CMAKE_ARGS}")
ExternalProject_Add(
    x265
    SOURCE_DIR ${X265_SOURCE_DIR}
    BINARY_DIR ${X265_BUILD_DIR}
    INSTALL_DIR ${X265_INSTALL_DIR}
    CMAKE_ARGS ${X265_CMAKE_ARGS}
    BUILD_COMMAND make -j
    INSTALL_COMMAND ${X265_INSTALL_COMMAND}
    LOG_CONFIGURE 1
    LOG_BUILD 1
    LOG_INSTALL 1
)